set_property(GLOBAL PROPERTY AD_BUILDTYPENAME_DEBUG "Debug")
set_property(GLOBAL PROPERTY AD_BUILDTYPENAME_DEV "Dev")
set_property(GLOBAL PROPERTY AD_BUILDTYPENAME_RELEASE "Shipping")

set_property(GLOBAL PROPERTY AD_BUILDTYPENAME_DEBUG_UPPER "DEBUG")
set_property(GLOBAL PROPERTY AD_BUILDTYPENAME_DEV_UPPER "DEV")
set_property(GLOBAL PROPERTY AD_BUILDTYPENAME_RELEASE_UPPER "SHIPPING")

set_property(GLOBAL PROPERTY AD_DEV_BUILD_LINKERFLAGS "DEBUG")


set_property(GLOBAL PROPERTY AD_CMAKE_RELPATH "Code/BuildSystem/CMake")
set_property(GLOBAL PROPERTY AD_CMAKE_RELPATH_CODE "Code")

set_property(GLOBAL PROPERTY AD_CONFIG_PATH_7ZA "")